channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.5
  - numpy=1.21.2
  - scipy=1.7.1
  - tqdm=4.62.3
  - ipython=7.29.0
  - cudatoolkit=11.3.1
  - pytorch::pytorch=1.10.0=py3.9_cuda11.3_cudnn8.2.0_0
